apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: qbench-server
  name: qbench-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbench-server
  template:
    metadata:
      labels:
        app: qbench-server
    spec:
      containers:
        - name: qbench-server
          image: quay.io/skupper/benchdog-qbench-server
          ports:
            - containerPort: 55672
