apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: qbench-server
  name: qbench-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbench-server
  template:
    metadata:
      labels:
        app: qbench-server
    spec:
      containers:
        - name: qbench-server
          image: quay.io/ssorj/benchdog-qbench-server
          ports:
            - containerPort: 55672
---
# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: qbench-server
#   name: qbench-server
# spec:
#   ports:
#   - port: 55672
#     protocol: TCP
#     targetPort: 55672
#   selector:
#     app: qbench-server
#   type: LoadBalancer
