apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wrk-server
  name: wrk-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wrk-server
  template:
    metadata:
      labels:
        app: wrk-server
    spec:
      containers:
        - name: wrk-server
          image: quay.io/skupper/benchdog-wrk-server
          ports:
            - containerPort: 58080
